FROM balenalib/%%BALENA_MACHINE_NAME%%-node:16

RUN install_packages build-essential python3 git openssh-client

WORKDIR /usr/src/app

COPY repo/package.json ./

RUN JOBS=MAX npm install --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY repo/ ./

#Build build svelte project to html
RUN npm run build:svelte

CMD ["node", "build/index.js"]
