version: "2"
volumes: 
  resin-data:
services:
  mongodb:
    image: mongo:4.2
    restart: always
    network_mode: 'host'
    volumes: 
      - 'resin-data:/data'
  nuster-turbine:
    build: ./
    network_mode: "host"
    depends_on: 
      - "mongodb"
    volumes:
      - "resin-data:/data"
    environment:
      DISABLE_AUTH: 'true'
  nuster-desktop:
    build: ./nuster-desktop/
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on: 
      - "nuster-turbine"
      - "mongodb"
  nuster-kiosk:
    build: ./nuster-kiosk/
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    depends_on:
      - 'nuster-desktop'
