version: "2"

volumes: 
  nuster-data:
  mongodb:
  settings:
  
services:
  mongodb:
    image: mongo:4.2
    restart: always
    network_mode: host
    volumes: 
      - mongodb:/data/db

  nuster-turbine:
    build: 
      dockerfile: ./packages/turbine/Dockerfile.draft.template
      context: ./
    network_mode: host
    privileged: true
    depends_on: 
      - "mongodb"
    volumes:
      - nuster-data:/data
    environment:
      DISABLE_AUTH: 'true'
    labels:
      io.balena.features.supervisor-api: '1'

  nuster-desktop:
    build: 
      dockerfile: ./packages/desktop/Dockerfile.draft.template
      context: ./
    restart: always
    network_mode: host
    depends_on: 
      - "nuster-turbine"
      - "mongodb"

  weston:
    image: bh.cr/igalia/Weston
    restart: always
    privileged: true
    volumes:
      - 'weston:/run/weston'

  wpe:
    image: bh.cr/wpe_webkit/browser-wpe
    restart: always
    privileged: true
    network_mode: host
    ports:
      - 8080:8080
      - 12321:12321
    volumes:
      - 'weston:/run/weston'
    environment:
      WPE_URL: http://127.0.0.1/
      WPE_COG_PLATFORM_FDO_VIEW_HEIGHT: 600
      WPE_COG_PLATFORM_FDO_VIEW_WIDTH: 1024
      GALLIUM_HUD: load+cpu+fps

  proxy: 
    build: ./containers/proxy/
    restart: always
    network_mode: host
    depends_on: 
      - "nuster-desktop"
      - "nuster-turbine"
      - "mongodb"

  wifi-connect:
    image: bh.cr/balenalabs/wifi-connect-aarch64
    restart: always
    network_mode: host
    privileged: true
    labels: 
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    cap_add:
      - NET_ADMIN
    environment:
      PORTAL_LISTENING_PORT: 8080
      PORTAL_SSID: 'Nuster Wifi Configurator'
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"