FROM balenalib/%%BALENA_MACHINE_NAME%%-node:17-buster

RUN install_packages build-essential python3 git openssh-client

WORKDIR /usr/src/app

COPY package.json ./

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY . ./

RUN npm run build

ENV NODE_ENV=production

CMD ["npm", "start"]