version: "2"

volumes: 
  nuster-data:
  mongodb:
  weston:
  
services:
  mongodb:
    image: mongo:4.2
    restart: always
    network_mode: host
    volumes: 
      - mongodb:/data/db

  proxy: 
    build: ./containers/proxy/
    restart: always
    network_mode: host

  weston:
    restart: always
    network_mode: host
    build:
      dockerfile: ./containers/weston/Dockerfile.template
      context: ./
    privileged: true
    volumes:
      - 'weston:/run/weston'
    environment:
      WPE_WESTON_OUTPUT_MAX_WIDTH: 1024
      WPE_WESTON_OUTPUT_MAX_HEIGHT: 600

  wifi-connect:
    image: bh.cr/balenalabs/wifi-connect-aarch64
    restart: always
    network_mode: host
    privileged: true
    labels: 
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    cap_add:
      - NET_ADMIN
    environment:
      PORTAL_LISTENING_PORT: 5000
      PORTAL_SSID: 'Nuster Wifi Configurator'
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  nuster-turbine:
    build: 
      dockerfile: ./packages/turbine/Dockerfile.template
      context: ./
    network_mode: host
    privileged: true
    volumes:
      - nuster-data:/data
    environment:
      DISABLE_AUTH: 'true'
    labels:
      io.balena.features.supervisor-api: '1'
    depends_on: 
      - "mongodb"

  nuster-desktop:
    build: 
      dockerfile: ./packages/desktop/Dockerfile.template
      context: ./
    restart: always
    network_mode: host
    depends_on: 
      - "nuster-turbine"
      - "proxy"
  
  wpe:
    restart: always
    network_mode: host
    build:
      dockerfile: ./containers/wpe/Dockerfile.template
      context: ./
    privileged: true
    volumes:
      - 'weston:/run/weston'
    environment:
      WPE_URL: 'http://127.0.0.1/'
      WPE_COG_PLATFORM_WL_VIEW_WIDTH: 1024
      WPE_COG_PLATFORM_WL_VIEW_HEIGHT: 600
    depends_on:
      - "nuster-desktop"
      - "nuster-turbine"
      - "proxy"
      - "weston"