version: "2"

volumes: 
  nuster-data:
  
services:
  mongodb:
    image: mongo:4.2
    restart: always
    network_mode: host
    volumes: 
      - 'nuster-data:/data'

  nuster-turbine:
    image: ghcr.io/metalizzsas/nusterturbine:main
    network_mode: host
    depends_on: 
      - "mongodb"
    volumes:
      - 'nuster-data:/data'
    environment:
      DISABLE_AUTH: 'true'
    labels:
      io.balena.features.supervisor-api: '1'

  nuster-desktop:
    image: ghcr.io/metalizzsas/nusterdesktop:main
    restart: always
    network_mode: host
    depends_on: 
      - "nuster-turbine"
      - "mongodb"

  nuster-kiosk:
    image: bh.cr/balenablocks/browser-aarch64
    privileged: true
    network_mode: host
    depends_on:
      - "nuster-turbine"
      - "mongodb"
      - 'nuster-desktop'
    environment:
      DISPLAY_NUM: 0
      LAUNCH_URL: 'http://127.0.0.1/'
      KIOSK: 1
      ENABLE_GPU: 1
      PERSISTANT: 1
      WINDOW_SIZE: 1024, 600
      #FLAGS: "--overscroll-history-navigation=0 --user-data-dir=/data/chromium-user-data"
    volumes:
      - 'nuster-data:/data'

  wifi-connect:
    image: bh.cr/balenablocks/wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels: 
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    cap_add:
      - NET_ADMIN
    environment:
      PORTAL_LISTENING_PORT: 8080
      PORTAL_SSID: 'Nuster Wifi Configurator'