version: "2"

volumes: 
  nuster-data:
  mongodb:
  weston:
  
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2.21
    restart: always
    volumes: 
      - mongodb:/data/db
    ports:
      - 27017:27017

  nuster-turbine:
    container_name: nuster-turbine
    build: 
      dockerfile: ./packages/turbine/Dockerfile.template
      context: ./
    privileged: true
    depends_on: 
      - "mongodb"
    volumes:
      - nuster-data:/data
    environment:
      MONGO_DB_URL: 'mongodb'
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    cap_add:
      - NET_ADMIN

  nuster-desktop:
    container_name: nuster-desktop
    build: 
      dockerfile: ./packages/desktop/Dockerfile.template
      context: ./
    restart: always
    depends_on: 
      - "nuster-turbine"
      - "mongodb"

  weston:
    restart: always
    build:
      dockerfile: ./containers/weston/Dockerfile.template
      context: ./
    privileged: true
    volumes:
      - 'weston:/run/weston'
    environment:
      WPE_WESTON_OUTPUT_MAX_WIDTH: 1024
      WPE_WESTON_OUTPUT_MAX_HEIGHT: 600
    
  wpe:
    restart: always
    build:
      dockerfile: ./containers/wpe/Dockerfile.template
      context: ./
    privileged: true
    volumes:
      - 'weston:/run/weston'
    environment:
      WPE_URL: 'http://proxy/'
      WPE_COG_PLATFORM_WL_VIEW_WIDTH: 1024
      WPE_COG_PLATFORM_WL_VIEW_HEIGHT: 600
    depends_on:
      - "weston"
      - "proxy"

  proxy: 
    container_name: proxy
    build: ./containers/proxy/
    restart: always
    depends_on: 
      - "nuster-desktop"
      - "nuster-turbine"
      - "mongodb"
    ports:
      - 80:80
      