import { IProfile } from "./Profile";

/**
 * Class used to explore Profiles generated by nuster
 * theese profile are stored in a mongoose database
 */
export class ProfileExplorer
{
    profile: IProfile;

    constructor(profile: IProfile)
    {
        this.profile = profile;
    }
    /**
     * Find a profile key in the profile object
     * @param key profile key
     * @returns result of this find, if result is undefined, the key mught be wrongly written or do not exists in the profile
     */
    public explore(key: string): number | undefined
    {
        const keyPath = key.split(".");
        return this.profile.fieldGroups.find((f) => f.name == keyPath[0])?.fields.find((f) => f.name == keyPath[1])?.value;
    }   
}

