export { call_to_action_routes } from "./calltoaction";
export { container_routes } from "./containers";
export { cycle_routes } from "./cycle";
export { io_routes } from "./io";
export { machine_routes } from "./machine";
export { maintenance_routes } from "./maintenances";
export { network_routes } from "./network";
export { profile_routes } from "./profiles";
export { system_routes } from "./system";
