FROM igalia/balena-browser-wpe:raspberrypi4-64-b7e469c

COPY containers/wpe/wpe-init /wpe-init
RUN chmod +x /wpe-init

COPY containers/wpe/cog-fdo /usr/bin/
RUN chmod +x /usr/bin/cog-fdo

COPY containers/wpe/cog-open /usr/bin/
RUN chmod +x /usr/bin/cog-open

CMD [ "/wpe-init" ]