name: 🚀 CI

on:
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  NODE_ENV: development

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Checkout repository
        uses: actions/checkout@v3

      - name: ⛏️ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: ⛏️ Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: 🗂️ Install packages 
        run: pnpm install --no-frozen-lockfile

      - name: 🔄 Sync packages
        run: pnpm run sync

      - name: ✔️ Run linting
        run: pnpm run lint

      - name: ✔️ Run tests
        run: pnpm test

      - name: 🧱 Build packages 
        run: pnpm run build