/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IParameterBlocks =
  | IAdditionParameterBlock
  | IConditionalParameterBlock
  | IConstantParameterBlock
  | IConstantStringParameterBlock
  | IIOReadParameterBlock
  | IMaintenanceParameterBlock
  | IMultiplyParameterBlock
  | IProfileParameterBlock
  | IReverseParameterBlock
  | ISlotLifetimeParameterBlock
  | IVariableParameterBlock
  | ISlotProductStatusParameterBlock;
export type INumericParameterBlock =
  | IAdditionParameterBlock
  | IConditionalParameterBlock
  | IConstantParameterBlock
  | IIOReadParameterBlock
  | IMaintenanceParameterBlock
  | IMultiplyParameterBlock
  | IProfileParameterBlock
  | IReverseParameterBlock
  | ISlotLifetimeParameterBlock
  | IVariableParameterBlock;
export type IProgramBlocks =
  | IForLoopProgramBlock
  | IGroupProgramBlock
  | IIfProgramBlock
  | IIOProgramBlock
  | IMaintenanceProgramBlock
  | ISleepProgramBlock
  | ISlotLoadProgramBlock
  | ISlotUnloadProgramBlock
  | IStartTimerProgramBlock
  | IStopProgramBlock
  | IStopTimerProgramBlock
  | IVariableProgramBlock
  | IWhileLoopProgramBlock
  | IPassiveProgramBlock;
export type EIOGateBus = "in" | "out";
export type EIOGateSize = "bit" | "word";
export type EIOGateType = "a10v" | "default" | "em4a10v" | "em4temp" | "um18";
export type EIOHandlerType = "em4" | "ex260s1" | "ex260s3" | "wago";
export type EProductSeries = "bc" | "cr" | "llc" | "tc" | "usl" | "wr";
export type ESlotSensorType = "level-a" | "level-max-n" | "level-min-n" | "level-np" | "temperature";

export interface Schema {
  cycles: {
    premades: IPBRPremades[];
    types: IProgram[];
    [k: string]: unknown;
  };
  iogates: IIOGate[];
  iohandlers: IIOHandler[];
  maintenance: IConfigMaintenance[];
  manual: IManualMode[];
  passives: IPassive[];
  profiles: {
    premades: IConfigProfile[];
    skeletons: IProfileSkeleton[];
    [k: string]: unknown;
  };
  slots: IConfigSlot[];
  [k: string]: unknown;
}
export interface IPBRPremades {
  cycle: string;
  name: string;
  profile: string;
  [k: string]: unknown;
}
export interface IProgram {
  name: string;
  profileRequired: boolean;
  startConditions: IPBRStartCondition[];
  steps: IProgramStep[];
  [k: string]: unknown;
}
export interface IPBRStartCondition {
  checkChain: IPBRSCCheckChain;
  conditionName: string;
  startOnly: boolean;
  [k: string]: unknown;
}
export interface IPBRSCCheckChain {
  io?: {
    gateName: string;
    gateValue: number;
    [k: string]: unknown;
  };
  name: "io" | "parameter";
  parameter?: IParameterBlocks;
  [k: string]: unknown;
}
export interface IAdditionParameterBlock {
  name: "add";
  params: INumericParameterBlock[];
  value?: string | number;
  [k: string]: unknown;
}
export interface IConditionalParameterBlock {
  name: "conditional";
  /**
   * @minItems 4
   * @maxItems 4
   */
  params: [
    INumericParameterBlock,
    INumericParameterBlock,
    (
      | IAdditionParameterBlock
      | IConditionalParameterBlock
      | IConstantParameterBlock
      | IConstantStringParameterBlock
      | IIOReadParameterBlock
      | IMaintenanceParameterBlock
      | IMultiplyParameterBlock
      | IProfileParameterBlock
      | IReverseParameterBlock
      | ISlotLifetimeParameterBlock
      | IVariableParameterBlock
      | ISlotProductStatusParameterBlock
    ),
    (
      | IAdditionParameterBlock
      | IConditionalParameterBlock
      | IConstantParameterBlock
      | IConstantStringParameterBlock
      | IIOReadParameterBlock
      | IMaintenanceParameterBlock
      | IMultiplyParameterBlock
      | IProfileParameterBlock
      | IReverseParameterBlock
      | ISlotLifetimeParameterBlock
      | IVariableParameterBlock
      | ISlotProductStatusParameterBlock
    )
  ];
  value: "!=" | "<" | "==" | ">";
  [k: string]: unknown;
}
export interface IConstantParameterBlock {
  name: "const";
  params?: IParameterBlocks[];
  value: number;
  [k: string]: unknown;
}
export interface IConstantStringParameterBlock {
  name: "conststr";
  params?: IParameterBlocks[];
  value: string;
  [k: string]: unknown;
}
export interface IIOReadParameterBlock {
  name: "io";
  params?: IParameterBlocks[];
  value: string;
  [k: string]: unknown;
}
export interface IMaintenanceParameterBlock {
  name: "maintenance";
  params?: IParameterBlocks[];
  value: string;
  [k: string]: unknown;
}
export interface IMultiplyParameterBlock {
  name: "multiply";
  params: INumericParameterBlock[];
  value?: string | number;
  [k: string]: unknown;
}
export interface IProfileParameterBlock {
  name: "profile";
  params?: IParameterBlocks[];
  value: string;
  [k: string]: unknown;
}
export interface IReverseParameterBlock {
  name: "reverse";
  /**
   * @minItems 1
   * @maxItems 1
   */
  params: [INumericParameterBlock];
  value?: string | number;
  [k: string]: unknown;
}
export interface ISlotLifetimeParameterBlock {
  name: "slotlife";
  params?: IParameterBlocks[];
  value: string;
  [k: string]: unknown;
}
export interface IVariableParameterBlock {
  name: "variable";
  params?: IParameterBlocks[];
  value: string;
  [k: string]: unknown;
}
export interface ISlotProductStatusParameterBlock {
  name: "slotstatus";
  params?: IParameterBlocks[];
  value: string;
  [k: string]: unknown;
}
export interface IProgramStep {
  blocks: IProgramBlocks[];
  duration: INumericParameterBlock;
  endBlocks: IProgramBlocks[];
  isEnabled: INumericParameterBlock;
  name: string;
  runAmount?: INumericParameterBlock;
  startBlocks: IProgramBlocks[];
  [k: string]: unknown;
}
export interface IForLoopProgramBlock {
  blocks: IProgramBlocks[];
  currentIteration?: number;
  executed?: boolean;
  name: "for";
  /**
   * @minItems 1
   * @maxItems 1
   */
  params: [INumericParameterBlock];
  [k: string]: unknown;
}
export interface IGroupProgramBlock {
  blocks: IProgramBlocks[];
  executed?: boolean;
  name: "group";
  params?: IParameterBlocks[];
  [k: string]: unknown;
}
export interface IIfProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  falseBlocks: IProgramBlocks[];
  name: "if";
  /**
   * @minItems 3
   * @maxItems 3
   */
  params: [
    INumericParameterBlock,
    IConstantStringParameterBlock | ISlotProductStatusParameterBlock,
    INumericParameterBlock
  ];
  trueBlocks: IProgramBlocks[];
  [k: string]: unknown;
}
export interface IIOProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "io";
  /**
   * @minItems 2
   * @maxItems 2
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock, INumericParameterBlock];
  [k: string]: unknown;
}
export interface IMaintenanceProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "maintenance";
  /**
   * @minItems 2
   * @maxItems 2
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock, INumericParameterBlock];
  [k: string]: unknown;
}
export interface ISleepProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "sleep";
  /**
   * @minItems 1
   * @maxItems 1
   */
  params: [INumericParameterBlock];
  [k: string]: unknown;
}
export interface ISlotLoadProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "slotLoad";
  /**
   * @minItems 1
   * @maxItems 1
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock];
  [k: string]: unknown;
}
export interface ISlotUnloadProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "slotUnload";
  /**
   * @minItems 1
   * @maxItems 1
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock];
  [k: string]: unknown;
}
export interface IStartTimerProgramBlock {
  blocks: IProgramBlocks[];
  executed?: boolean;
  name: "startTimer";
  /**
   * @minItems 2
   * @maxItems 2
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock, INumericParameterBlock];
  [k: string]: unknown;
}
export interface IStopProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "stop";
  /**
   * @minItems 1
   * @maxItems 1
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock];
  [k: string]: unknown;
}
export interface IStopTimerProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "stopTimer";
  /**
   * @minItems 1
   * @maxItems 1
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock];
  [k: string]: unknown;
}
export interface IVariableProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "variable";
  /**
   * @minItems 2
   * @maxItems 2
   */
  params: [IConstantStringParameterBlock | ISlotProductStatusParameterBlock, INumericParameterBlock];
  [k: string]: unknown;
}
export interface IWhileLoopProgramBlock {
  blocks: IProgramBlocks[];
  executed?: boolean;
  name: "while";
  /**
   * @minItems 3
   * @maxItems 3
   */
  params: [
    INumericParameterBlock,
    IConstantStringParameterBlock | ISlotProductStatusParameterBlock,
    INumericParameterBlock
  ];
  [k: string]: unknown;
}
export interface IPassiveProgramBlock {
  blocks?: IProgramBlocks[];
  executed?: boolean;
  name: "passive";
  /**
   * @minItems 3
   * @maxItems 3
   */
  params: [
    IConstantStringParameterBlock | ISlotProductStatusParameterBlock,
    INumericParameterBlock,
    INumericParameterBlock
  ];
  [k: string]: unknown;
}
export interface IIOGate {
  address: number;
  automaton: number;
  bus: EIOGateBus;
  default: number;
  isCritical?: boolean;
  manualModeWatchdog?: boolean;
  name: string;
  size: EIOGateSize;
  type: EIOGateType;
  [k: string]: unknown;
}
export interface IIOHandler {
  ip: string;
  name: string;
  type: EIOHandlerType;
  [k: string]: unknown;
}
export interface IConfigMaintenance {
  duration?: number;
  durationLimit: number;
  durationType: string;
  name: string;
  operationDate?: number;
  procedure?: IMaintenanceProcedure;
  [k: string]: unknown;
}
export interface IMaintenanceProcedure {
  steps: IMaintenanceProcedureStep[];
  tools: string[];
  [k: string]: unknown;
}
export interface IMaintenanceProcedureStep {
  media: string[];
  name: string;
  [k: string]: unknown;
}
export interface IManualMode {
  analogScale?: {
    max: number;
    min: number;
    [k: string]: unknown;
  };
  controls: (
    | {
        analogScaleDependant: boolean;
        name: string;
        [k: string]: unknown;
      }
    | string
  )[];
  incompatibility?: string[];
  name: string;
  requires?: string[];
  watchdog?: IManualWatchdogCondition[];
  [k: string]: unknown;
}
export interface IManualWatchdogCondition {
  gateName: string;
  gateValue: number;
  [k: string]: unknown;
}
export interface IPassive {
  actuators: {
    minus?: string[] | string;
    plus: string[] | string;
    [k: string]: unknown;
  };
  manualModes?: string[] | string;
  name: string;
  sensors: string[] | string;
  target: number;
  [k: string]: unknown;
}
export interface IConfigProfile {
  isPremade: boolean;
  modificationDate?: number;
  name: string;
  overwriteable: boolean;
  removable: boolean;
  skeleton: string;
  values: {
    [k: string]: number | boolean;
  };
  [k: string]: unknown;
}
export interface IProfileSkeleton {
  fieldGroups: IProfileSkeletonFieldGroup[];
  identifier: string;
  [k: string]: unknown;
}
export interface IProfileSkeletonFieldGroup {
  fields: (
    | (IProfileSkeletonFieldFloat & IProfileSkeletonField)
    | (IProfileSkeletonFieldBoolean & IProfileSkeletonField)
    | (IProfileSkeletonFieldNumber & IProfileSkeletonField)
    | (IProfileSkeletonFieldTime & IProfileSkeletonField)
  )[];
  name: string;
  [k: string]: unknown;
}
export interface IProfileSkeletonFieldFloat {
  floatMax: number;
  floatMin: number;
  floatStep: number;
  name: string;
  type: "float";
  unity?: string;
  value: number;
  [k: string]: unknown;
}
export interface IProfileSkeletonField {
  name: string;
  type: "bool" | "float" | "int" | "time";
  unity?: string;
  value: number | boolean;
  [k: string]: unknown;
}
export interface IProfileSkeletonFieldBoolean {
  name: string;
  type: "bool";
  unity?: string;
  value: boolean;
  [k: string]: unknown;
}
export interface IProfileSkeletonFieldNumber {
  name: string;
  type: "int";
  unity?: string;
  value: number;
  [k: string]: unknown;
}
export interface IProfileSkeletonFieldTime {
  name: string;
  type: "time";
  unity?: string;
  value: number;
  [k: string]: unknown;
}
export interface IConfigSlot {
  callToAction?: ICallToAction[];
  name: string;
  productOptions?: ISlotProductOptions;
  sensors: ISlotSensor[];
  type: string;
  [k: string]: unknown;
}
export interface ICallToAction {
  APIEndpoint?: {
    method: "delete" | "get" | "post" | "put";
    url: string;
    [k: string]: unknown;
  };
  UIEndpoint?: string;
  name: string;
  [k: string]: unknown;
}
export interface ISlotProductOptions {
  defaultProductSeries: EProductSeries;
  lifespan: number;
  [k: string]: unknown;
}
export interface ISlotSensor {
  io: string;
  type: ESlotSensorType;
  value?: number;
  [k: string]: unknown;
}
