/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaAddon {
  /**
   * Addon name, should be the same as the Json file holding him
   */
  addonName: string;
  /**
   * Addon content Array
   */
  content: IAddonContent[];
  [k: string]: unknown;
}
export interface IAddonContent {
  /**
   * Content replaced or inserted to this category
   */
  content: {
    [k: string]: unknown;
  };
  /**
   * Insertion mode
   */
  mode: "merge" | "replace";
  /**
   * Path were the content is added
   */
  path: string;
  [k: string]: unknown;
}
